/**
 * Auto-Fix PR Generator — creates draft PRs from AI attribution results.
 *
 * Flow: create branch → write patch → git apply → commit → push → gh pr create --draft.
 * All PRs are draft-only as a safety invariant.
 */

import type { AIAttributionResult, AutoFixPROptions, AutoFixPRResult } from '../types.js';

// ===== Executor abstraction (injectable for tests) =====

export interface GitExecutor {
  exec(command: string, args: string[]): Promise<{ stdout: string; exitCode: number }>;
}

export interface PatchWriter {
  write(path: string, content: string): Promise<void>;
  mkdir(dir: string): Promise<void>;
}

// ===== Defaults =====

const DEFAULT_OPTIONS: Required<AutoFixPROptions> = {
  branchPrefix: 'autofix/',
  baseBranch: 'main',
  draftOnly: true,
};

// ===== Core =====

export async function generateFixPR(
  attribution: AIAttributionResult,
  git: GitExecutor,
  patchWriter: PatchWriter,
  options?: AutoFixPROptions,
): Promise<AutoFixPRResult> {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const branch = `${opts.branchPrefix}${ts}`;
  const patchFile = `report/patch-${ts}.patch`;

  // Create branch
  await git.exec('git', ['checkout', '-b', branch]);

  // Write patch
  await patchWriter.mkdir('report');
  await patchWriter.write(patchFile, attribution.fixSuggestion.codePatch);

  // Apply patch (non-fatal if fails)
  try {
    await git.exec('git', ['apply', patchFile]);
  } catch {
    // Patch may not apply cleanly — continue anyway
  }

  // Stage, commit, push
  await git.exec('git', ['add', '.']);
  await git.exec('git', ['commit', '-m', `fix: AI auto-patch for "${attribution.testName}"`]);
  await git.exec('git', ['push', 'origin', branch]);

  // Create draft PR (always draft for safety)
  const prArgs = [
    'pr', 'create', '--draft',
    '--title', `[AI Fix] ${attribution.testName}`,
    '--body', buildPRBody(attribution),
  ];
  const { stdout: prUrl } = await git.exec('gh', prArgs);

  // Return to base branch
  await git.exec('git', ['checkout', opts.baseBranch]);

  return { prUrl: prUrl.trim(), branch, patchFile };
}

function buildPRBody(a: AIAttributionResult): string {
  return [
    '## AI Auto-Fix PR',
    '',
    `**Test:** ${a.testName}`,
    `**Category:** ${a.category} | **Severity:** ${a.severity} | **Confidence:** ${(a.confidence * 100).toFixed(0)}%`,
    '',
    '### Root Cause',
    a.rootCause,
    '',
    '### Fix',
    a.fixSuggestion.description,
    '',
    '---',
    '> This PR was auto-generated by AI and **must be reviewed before merging**.',
  ].join('\n');
}
