/**
 * CI template generators for popular CI/CD platforms.
 *
 * Usage:
 *   npx opencroc ci --platform=github
 *   npx opencroc ci --platform=gitlab
 */

export interface CiTemplateOptions {
  /** Node.js version(s). Default: ['20.x'] */
  nodeVersions?: string[];
  /** Install command. Default: 'npm ci' */
  installCommand?: string;
  /** Whether to run self-healing. Default: false */
  selfHeal?: boolean;
  /** Custom opencroc generate args */
  generateArgs?: string;
  /** Custom opencroc test args */
  testArgs?: string;
}

export function generateGitHubActionsTemplate(opts: CiTemplateOptions = {}): string {
  const nodeVersions = opts.nodeVersions ?? ['20.x'];
  const install = opts.installCommand ?? 'npm ci';
  const genArgs = opts.generateArgs ?? '--all';
  const testArgs = opts.testArgs ?? '';
  const healStep = opts.selfHeal
    ? `
      - name: Self-heal failures
        if: failure()
        run: npx opencroc heal --max-iterations 3`
    : '';

  const matrix =
    nodeVersions.length > 1
      ? `
    strategy:
      matrix:
        node-version: [${nodeVersions.join(', ')}]`
      : '';

  const nodeSetup =
    nodeVersions.length > 1
      ? '${{ matrix.node-version }}'
      : nodeVersions[0];

  return `# Generated by OpenCroc — AI-native E2E testing
# https://github.com/opencroc/opencroc

name: OpenCroc E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest${matrix}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '${nodeSetup}'

      - name: Install dependencies
        run: ${install}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Generate E2E tests
        run: npx opencroc generate ${genArgs}

      - name: Run E2E tests
        run: npx opencroc test ${testArgs}
${healStep}
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: opencroc-report
          path: opencroc-output/
          retention-days: 14
`;
}

export function generateGitLabCITemplate(opts: CiTemplateOptions = {}): string {
  const install = opts.installCommand ?? 'npm ci';
  const genArgs = opts.generateArgs ?? '--all';
  const testArgs = opts.testArgs ?? '';
  const nodeVersion = opts.nodeVersions?.[0] ?? '20';

  return `# Generated by OpenCroc — AI-native E2E testing
# https://github.com/opencroc/opencroc

image: node:${nodeVersion}

stages:
  - generate
  - test

variables:
  PLAYWRIGHT_BROWSERS_PATH: \${CI_PROJECT_DIR}/.cache/ms-playwright

cache:
  key: \${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cache/ms-playwright/

generate:
  stage: generate
  script:
    - ${install}
    - npx opencroc generate ${genArgs}
  artifacts:
    paths:
      - opencroc-output/
    expire_in: 1 day

e2e:
  stage: test
  needs: [generate]
  before_script:
    - ${install}
    - npx playwright install --with-deps chromium
  script:
    - npx opencroc test ${testArgs}
  artifacts:
    when: always
    paths:
      - opencroc-output/
    expire_in: 14 days
`;
}

const TEMPLATES: Record<string, (opts: CiTemplateOptions) => string> = {
  github: generateGitHubActionsTemplate,
  gitlab: generateGitLabCITemplate,
};

/**
 * Get available CI platform names.
 */
export function listCiPlatforms(): string[] {
  return Object.keys(TEMPLATES);
}

/**
 * Generate a CI template for the given platform.
 */
export function generateCiTemplate(
  platform: string,
  opts: CiTemplateOptions = {},
): string {
  const generator = TEMPLATES[platform];
  if (!generator) {
    throw new Error(
      `Unknown CI platform: "${platform}". Available: ${Object.keys(TEMPLATES).join(', ')}`,
    );
  }
  return generator(opts);
}
